#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.1.11:3306/gulimall_ums
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: gulimall-member
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 8000

spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 80648af0-b788-4048-8800-c67f2e927dc1
  config:
    import:
      - nacos:datasource.yml?group=dev
      - nacos:mybatis.yml?group=dev
      - nacos:other.yml?group=dev

  application:
    name: gulimall-member