#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.1.11:3306/gulimall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 714c842f-40fe-4009-992d-c896101b67d3
#  config:
#    import: nacos:${spring.application.name}.properties
#
#  application:
#    name: gulimall-coupon
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 7000

spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 714c842f-40fe-4009-992d-c896101b67d3
  config:
    import:
      - nacos:${spring.application.name}.properties?group=dev
      - nacos:datasource.yml?group=dev
      - nacos:mybatis.yml?group=dev
      - nacos:other.yml?group=dev

  application:
    name: gulimall-coupon

